[phases.setup]
nixPkgs = [
  "python311",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "gobject-introspection",
  "harfbuzz",
  "libffi",
  "zlib",
  "fontconfig",
]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]
